# Generated by Django 5.2.7 on 2025-11-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0003_alter_book_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="library",
            name="books",
        ),
        migrations.RemoveField(
            model_name="librarian",
            name="library",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Librarian",
        ),
        migrations.DeleteModel(
            name="Library",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
